<a href="https://colab.research.google.com/github/Roni81/ultra_roni/blob/main/BERT_day1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install transformers

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.9/7.9 MB 47.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 311.1/311.1 kB 33.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.8/3.8 MB 40.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 52.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 295.0/295.0 kB 27.8 MB/s eta 0:00:00


In [5]:
import pandas as pd
from transformers import BertTokenizer

In [7]:
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

In [9]:
result = tokenizer.tokenize('Here is the sentence I want embeddings for.')
print(result)

['here', 'is', 'the', 'sentence', 'i', 'want', 'em', '##bed', '##ding', '##s', 'for', '.']


In [10]:
from transformers import TFBertForMaskedLM

In [11]:
model = TFBertForMaskedLM.from_pretrained('bert-large-uncased')
#BERT를 마스크드 언어 모델 구조로 읽어들인다.

All PyTorch model weights were used when initializing TFBertForMaskedLM.

All the weights of TFBertForMaskedLM were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertForMaskedLM for predictions without further training.


In [12]:
from transformers import AutoTokenizer

In [13]:
tokenizer = AutoTokenizer.from_pretrained("bert-large-uncased")
#bert-large-uncase 모델이 학습될 당시에 사용된 토크나이저가 읽어진다

In [14]:
# A라는 버트토크나이저에서는 '사과'를 40번으로 인코딩
# B라는 버트 토크나이저에서는 50번으로 인코딩

In [15]:
inputs = tokenizer('Soccer is a really fun [MASK].', return_tensors = 'tf')

In [16]:
inputs

{'input_ids': <tf.Tensor: shape=(1, 9), dtype=int32, numpy=
array([[ 101, 4715, 2003, 1037, 2428, 4569,  103, 1012,  102]],
      dtype=int32)>, 'token_type_ids': <tf.Tensor: shape=(1, 9), dtype=int32, numpy=array([[0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(1, 9), dtype=int32, numpy=array([[1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int32)>}

In [17]:
inputs['token_type_ids']

<tf.Tensor: shape=(1, 9), dtype=int32, numpy=array([[0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)>

In [20]:
inputs

{'input_ids': <tf.Tensor: shape=(1, 9), dtype=int32, numpy=
array([[ 101, 4715, 2003, 1037, 2428, 4569,  103, 1012,  102]],
      dtype=int32)>, 'token_type_ids': <tf.Tensor: shape=(1, 9), dtype=int32, numpy=array([[0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(1, 9), dtype=int32, numpy=array([[1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int32)>}

In [21]:
inputs['attention_mask']

<tf.Tensor: shape=(1, 9), dtype=int32, numpy=array([[1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int32)>

In [22]:
from transformers import FillMaskPipeline

In [23]:
 pip = FillMaskPipeline(model = model, tokenizer = tokenizer)

In [26]:
pip('Soccer is a really fun [MASK]')

[{'score': 0.9753890037536621,
  'token': 1012,
  'token_str': '.',
  'sequence': 'soccer is a really fun.'},
 {'score': 0.014161501079797745,
  'token': 999,
  'token_str': '!',
  'sequence': 'soccer is a really fun!'},
 {'score': 0.009934996254742146,
  'token': 1025,
  'token_str': ';',
  'sequence': 'soccer is a really fun ;'},
 {'score': 0.00047694394015707076,
  'token': 1029,
  'token_str': '?',
  'sequence': 'soccer is a really fun?'},
 {'score': 1.8595377696328796e-05,
  'token': 2133,
  'token_str': '...',
  'sequence': 'soccer is a really fun...'}]

In [27]:
pip('I want to [MASK] this morning')

[{'score': 0.32640865445137024,
  'token': 2681,
  'token_str': 'leave',
  'sequence': 'i want to leave this morning'},
 {'score': 0.1251135915517807,
  'token': 2707,
  'token_str': 'start',
  'sequence': 'i want to start this morning'},
 {'score': 0.0632697194814682,
  'token': 3280,
  'token_str': 'die',
  'sequence': 'i want to die this morning'},
 {'score': 0.04291823133826256,
  'token': 2175,
  'token_str': 'go',
  'sequence': 'i want to go this morning'},
 {'score': 0.03469858318567276,
  'token': 3637,
  'token_str': 'sleep',
  'sequence': 'i want to sleep this morning'}]

In [28]:
#한국어 bert

In [29]:
model = TFBertForMaskedLM.from_pretrained('klue/bert-base', from_pt=True)

Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFBertForMaskedLM: ['bert.embeddings.position_ids', 'cls.predictions.decoder.bias']
- This IS expected if you are initializing TFBertForMaskedLM from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertForMaskedLM from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFBertForMaskedLM were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertForMaskedLM for predictions without further training.


In [30]:
tokenizer = AutoTokenizer.from_pretrained("klue/bert-base")

In [35]:
inputs = tokenizer('축구는 정말 재미있는 [MASK]다.', return_tensors = 'tf')


In [36]:
pip('축구는 정말 재미있는 [MASK]다.')

[{'score': 0.27445146441459656,
  'token': 100,
  'token_str': '[UNK]',
  'sequence': '축구는 정말 다.'},
 {'score': 0.2643638849258423,
  'token': 1011,
  'token_str': '-',
  'sequence': '축구는 정말 - 다.'},
 {'score': 0.21644102036952972,
  'token': 1012,
  'token_str': '.',
  'sequence': '축구는 정말. 다.'},
 {'score': 0.10372215509414673,
  'token': 1010,
  'token_str': ',',
  'sequence': '축구는 정말, 다.'},
 {'score': 0.028204675763845444,
  'token': 1024,
  'token_str': ':',
  'sequence': '축구는 정말 : 다.'}]

In [33]:
inputs

{'input_ids': <tf.Tensor: shape=(1, 10), dtype=int32, numpy=
array([[   2, 4713, 2259, 3944, 6001, 2259,    4,  809,   18,    3]],
      dtype=int32)>, 'token_type_ids': <tf.Tensor: shape=(1, 10), dtype=int32, numpy=array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(1, 10), dtype=int32, numpy=array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int32)>}

In [34]:
pip('나는 내일 [MASK]를 본다')

[{'score': 0.7539768218994141,
  'token': 100,
  'token_str': '[UNK]',
  'sequence': '나는 내일 를 본다'},
 {'score': 0.12203676998615265,
  'token': 1010,
  'token_str': ',',
  'sequence': '나는 내일, 를 본다'},
 {'score': 0.024064913392066956,
  'token': 1011,
  'token_str': '-',
  'sequence': '나는 내일 - 를 본다'},
 {'score': 0.018377697095274925,
  'token': 30021,
  'token_str': '##ᆫ',
  'sequence': '나는 내일ᆫ 를 본다'},
 {'score': 0.014864356257021427,
  'token': 1025,
  'token_str': ';',
  'sequence': '나는 내일 ; 를 본다'}]

In [37]:
from transformers import TFBertForNextSentencePrediction

In [38]:
from transformers import AutoTokenizer

In [39]:
model = TFBertForNextSentencePrediction.from_pretrained('bert-base-uncased')

All PyTorch model weights were used when initializing TFBertForNextSentencePrediction.

All the weights of TFBertForNextSentencePrediction were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertForNextSentencePrediction for predictions without further training.


In [40]:
tokenizer = AutoTokenizer.from_pretrained('bert-base-uncased')

In [64]:
prompt = "In Italy, pizza served in formal settings, such as at a restaurant, is presented unsliced."
next_sentence = "The sky is blue due to the shorter wavelength of blue light."

In [65]:
encoding = tokenizer(prompt, next_sentence, return_tensors='tf')

In [66]:
encoding

{'input_ids': <tf.Tensor: shape=(1, 38), dtype=int32, numpy=
array([[  101,  1999,  3304,  1010, 10733,  2366,  1999,  5337, 10906,
         1010,  2107,  2004,  2012,  1037,  4825,  1010,  2003,  3591,
         4895, 14540,  6610,  2094,  1012,   102,  1996,  3712,  2003,
         2630,  2349,  2000,  1996,  7820, 19934,  1997,  2630,  2422,
         1012,   102]], dtype=int32)>, 'token_type_ids': <tf.Tensor: shape=(1, 38), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(1, 38), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int32)>}

In [67]:
pip( "In Italy, [MASK] served in formal settings, such as at a restaurant, is presented unsliced.")

[{'score': 0.6597473621368408,
  'token': 2833,
  'token_str': 'food',
  'sequence': 'in italy, food served in formal settings, such as at a restaurant, is presented unsliced.'},
 {'score': 0.07964400202035904,
  'token': 10733,
  'token_str': 'pizza',
  'sequence': 'in italy, pizza served in formal settings, such as at a restaurant, is presented unsliced.'},
 {'score': 0.030377013608813286,
  'token': 4157,
  'token_str': 'coffee',
  'sequence': 'in italy, coffee served in formal settings, such as at a restaurant, is presented unsliced.'},
 {'score': 0.02620113641023636,
  'token': 4511,
  'token_str': 'wine',
  'sequence': 'in italy, wine served in formal settings, such as at a restaurant, is presented unsliced.'},
 {'score': 0.02576436661183834,
  'token': 6240,
  'token_str': 'meat',
  'sequence': 'in italy, meat served in formal settings, such as at a restaurant, is presented unsliced.'}]

In [68]:
pip('in Korea, [MASK] served in formal setting, such as at a home')

[{'score': 0.14225125312805176,
  'token': 5572,
  'token_str': 'tea',
  'sequence': 'in korea, tea served in formal setting, such as at a home'},
 {'score': 0.1168249249458313,
  'token': 2009,
  'token_str': 'it',
  'sequence': 'in korea, it served in formal setting, such as at a home'},
 {'score': 0.08757320046424866,
  'token': 2027,
  'token_str': 'they',
  'sequence': 'in korea, they served in formal setting, such as at a home'},
 {'score': 0.06990186125040054,
  'token': 10447,
  'token_str': 'dishes',
  'sequence': 'in korea, dishes served in formal setting, such as at a home'},
 {'score': 0.06916830688714981,
  'token': 2833,
  'token_str': 'food',
  'sequence': 'in korea, food served in formal setting, such as at a home'}]

In [69]:
model(encoding['input_ids'], encoding['token_type_ids'])

TFNextSentencePredictorOutput(loss=None, logits=<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[ 3.7495365, -2.7508059]], dtype=float32)>, hidden_states=None, attentions=None)

In [70]:
logits = model(encoding['input_ids'], encoding['token_type_ids'])[0]

In [71]:
import tensorflow as  tf

In [72]:
print(tf.keras.layers.Softmax(logits))

In [73]:
soft = tf.keras.layers.Softmax()
res = soft(logits)

In [74]:
res

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[0.9984994 , 0.00150067]], dtype=float32)>

In [75]:
tf.math.argmax(res, axis = -1).numpy()
#0이면 이어지는 문장

array([0])