In [2]:
pip install torch


   ---------------------------------------- 0.0/192.3 MB ? eta -:--:--
   ---------------------------------------- 0.6/192.3 MB 11.5 MB/s eta 0:00:17
   ---------------------------------------- 1.1/192.3 MB 11.7 MB/s eta 0:00:17
   ---------------------------------------- 1.6/192.3 MB 11.6 MB/s eta 0:00:17
   ---------------------------------------- 2.2/192.3 MB 11.6 MB/s eta 0:00:17
    --------------------------------------- 2.7/192.3 MB 11.6 MB/s eta 0:00:17
    --------------------------------------- 3.3/192.3 MB 11.7 MB/s eta 0:00:17
    --------------------------------------- 3.8/192.3 MB 11.6 MB/s eta 0:00:17
    --------------------------------------- 4.4/192.3 MB 11.6 MB/s eta 0:00:17
   - -------------------------------------- 4.9/192.3 MB 11.6 MB/s eta 0:00:17
   - -------------------------------------- 5.4/192.3 MB 11.6 MB/s eta 0:00:17
   - -------------------------------------- 6.0/192.3 MB 11.5 MB/s eta 0:00:17
   - -------------------------------------- 6.5/192.3 MB 11

In [5]:
import numpy as np

In [3]:
import torch

In [9]:
t=torch.FloatTensor([0.,1.,2.,3.,4.,5.,6.])
t
#클래스(FloatTensor): 대문자로 시작

tensor([0., 1., 2., 3., 4., 5., 6.])

In [10]:
t.dim()

1

In [11]:
t.shape

torch.Size([7])

In [12]:
t.size()

torch.Size([7])

In [ ]:
# 클래스 : 설계도면, 붕어빵기계, 벽돌공장
#객체 : 클래스로부터 생성 되는 실체
#설계도면 -> 실제 건물
# 붕어빵기계 -> 붕어빵
#벽돌공장 -> 벽돌
#메서드 : 객체가 수행하는 동장(기능)
# 속성(어트리뷰트) : 객체의 특성
#객체지향(적) 프로그래밍 :

ex) 절차 지향적 사례
- 붕아빵기계로 붕어빵을 판매하던 시대가 지나고
 잉

In [8]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
t

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])

In [6]:

[0., 1., 2., 3., 4., 5., 6.]

[0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0]

In [13]:
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                      ])

In [15]:
t[:,0].size()

torch.Size([4])

In [16]:
#행렬 연산(덧셈, 뺄셈) : 두 행렬의 크기가 같아야 함
#행렬 연산(곱셈) : 두 행렬의 마지막 차원과 첫번째 차원이 일치

In [17]:
#브로드 캐스팅 == 행렬의 크기를 맞춰서 연산이 가능하도록 만듬

In [18]:
t1 = torch.FloatTensor([[1,1]])
t2 = torch.FloatTensor([[2,2]])

In [19]:
t1+ t2

tensor([[3., 3.]])

In [20]:
t3 = torch.FloatTensor([[1,1]])
t4 = torch.FloatTensor([[3]])

In [56]:
t3.shape

torch.Size([1, 2])

In [21]:
t3+t4 #shape을 맞춰서 연산이 가능 하게 만듬

tensor([[4., 4.]])

In [22]:
t5 = torch.FloatTensor([[1,3]])
t6 = torch.FloatTensor([[1],[3]])

In [23]:
t5.shape

torch.Size([1, 2])

In [24]:
t6.shape

torch.Size([2, 1])

In [26]:
t5

tensor([[1., 3.]])

In [27]:
t6

tensor([[1.],
        [3.]])

In [25]:
t5+t6

tensor([[2., 4.],
        [4., 6.]])

In [28]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])

In [29]:
m1

tensor([[1., 2.],
        [3., 4.]])

In [52]:
m1.shape

torch.Size([2, 2])

In [30]:
m2

tensor([[1.],
        [2.]])

In [53]:
m2.shape

torch.Size([2, 1])

In [50]:
mm = m1.matmul(m2)

In [54]:
mm

tensor([[ 5.],
        [11.]])

In [51]:
mm.shape

torch.Size([2, 1])

In [32]:
m1 * m2 #요소간 곱샘 브로드 캐스팅으로 행렬의 크기를 맞춰서 각각 위치에 맞는 수 끼리 곱함

tensor([[1., 2.],
        [6., 8.]])

In [37]:
t=torch.FloatTensor([[1,2],[3,4]])
t

tensor([[1., 2.],
        [3., 4.]])

In [38]:
t.mean()

tensor(2.5000)

In [39]:
t.mean(dim=0)  #dim = 0은 첫번째 차원, 행렬에서는 행, 행을 제거 -> 열만 남음

tensor([2., 3.])

In [40]:
t.mean(dim = 1) #dim = 1은 두번째 차원, 행렬에서는 열, 열을 제거 -> 행만 남음

tensor([1.5000, 3.5000])

In [293]:
t=torch.FloatTensor([[1,2],[3,4]])

In [294]:
t.min()

tensor(1.)

In [295]:
t.min(dim=0)

torch.return_types.min(
values=tensor([1., 2.]),
indices=tensor([0, 0]))

In [296]:
t.min(dim=1)

torch.return_types.min(
values=tensor([1., 3.]),
indices=tensor([0, 0]))

In [42]:
t.sum()

tensor(10.)

In [43]:
t.sum(dim=0)

tensor([4., 6.])

In [44]:
t.sum(dim=1)

tensor([3., 7.])

In [45]:
t.sum(dim=-1) #마지막 차원 제거(열 제거)

tensor([3., 7.])

In [46]:
t

tensor([[1., 2.],
        [3., 4.]])

In [47]:
t.max()

tensor(4.)

In [48]:
t.max(dim=0) #행제거 indices(argmax) : 최대값의 인덱스

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))

In [298]:
t.min(dim=1)

torch.return_types.min(
values=tensor([1., 3.]),
indices=tensor([0, 0]))

In [297]:
t.min(dim=0)

torch.return_types.min(
values=tensor([1., 2.]),
indices=tensor([0, 0]))

In [49]:
t.max(dim = 1)

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))

In [300]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)

In [301]:
t

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [302]:
ft

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]])

In [58]:
ft.shape

torch.Size([2, 2, 3])

In [304]:
ft.view([-1,3])

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])

In [60]:
# view : 텐서 크기 변경  (-1, 3)의미는 (?, 3) 첫번째 차원은 모르고 두번째 차원의 크기는 3
# 12개의 요소로 되어 있는 3차원 텐서  -> 2번째 차원을 지정했으니 1번째 차원의 크기는 4

In [61]:
ft.view([4,-1])

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])

In [62]:
ft.view([5,-1])

RuntimeError: shape '[5, -1]' is invalid for input of size 12

In [63]:
ft.view([3,-1])

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [64]:
ft.view([-1, 1, 3])

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])

In [306]:
ft = torch.FloatTensor([[0],[1],[2]])
ft

tensor([[0.],
        [1.],
        [2.]])

In [307]:
ft.shape

torch.Size([3, 1])

In [70]:
ft.squeeze()  #크기가 1인 차원을 제거

tensor([0., 1., 2.])

In [308]:
ft.squeeze().shape

torch.Size([3])

In [ ]:
ft2 = torch.FloatTensor([[0,1],[1,2],[2,3]])

In [71]:
ft2.squeeze() #크기가 1인 차원이 없으므로 제거 하지 않음

tensor([[0., 1.],
        [1., 2.],
        [2., 3.]])

In [ ]:
#unsqueeze : 크기가 1인 차원을 특정 위치에 추가                                                                                    

In [73]:
ft = torch.Tensor([0, 1, 2])
ft

tensor([0., 1., 2.])

In [309]:
ft.shape

torch.Size([3, 1])

In [310]:
ft.squeeze().shape # 크기가 1인 차원만 존재할때는 제거하지 않음

torch.Size([3])

In [75]:
ft.unsqueeze(1)  #(3,1)

tensor([[0.],
        [1.],
        [2.]])

In [76]:
ft.unsqueeze(0)  #(1,3)

tensor([[0., 1., 2.]])

In [77]:
lt = torch.LongTensor([1, 2, 3, 4])
print(lt)

tensor([1, 2, 3, 4])


In [78]:
lt = torch.LongTensor([1., 2, 3, 4])
print(lt) #LongTensor는 int 타입의 한 종류  1. => 1로 변환되서 출력

tensor([1, 2, 3, 4])


In [79]:
lt.float()

tensor([1., 2., 3., 4.])

In [80]:
bt = torch.ByteTensor([True, False, True, False])
print(bt)

tensor([1, 0, 1, 0], dtype=torch.uint8)


In [81]:
bt.long()

tensor([1, 0, 1, 0])

In [ ]:
bt2 = torch.ByteTensor([True, False, True, False])
print(bt)

In [82]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

In [83]:
x

tensor([[1., 2.],
        [3., 4.]])

In [84]:
y

tensor([[5., 6.],
        [7., 8.]])

In [86]:
torch.cat([x,y], dim=0) #첫번째 차원을 기준으로 연결됨

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])

In [87]:
torch.cat([x,y], dim=1) #두번째 차원을 기준으로 연결됨

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])

In [88]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

In [89]:
z

tensor([3., 6.])

In [90]:
xyz = torch.stack([x,y,z])

In [91]:
xyz

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])

In [92]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [93]:
torch.ones_like(x)
torch.zeros_like(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [94]:
x = torch.FloatTensor([[1, 2], [3, 4]])

In [96]:
x*2

tensor([[2., 4.],
        [6., 8.]])

In [101]:
x.mul(2)

tensor([[12., 24.],
        [36., 48.]])

tensor([[2., 4.],
        [6., 8.]])

In [102]:
result = 0 
# 함수 바깥의 변수 == 전역변수

In [106]:
def add(num):
    result = 1
    #함수 내에서만 사용되는 변수 == 지역변수
    result+=num
    return result

In [107]:
add(3)

4

In [108]:
print(result)

0


In [128]:
result1 = 0
result2 = 0

In [129]:
def add1(num):
    global result1
    result1 += num
    return result1

In [130]:
def add2(num):
    global result2
    result2 += num
    return result2

In [131]:
print(result1)

0


In [132]:
print(add1(3))  # add1 내에서 누적됨
print(add1(4))
print(add1(4))


3
7
11


In [133]:
print(result1)

11


In [126]:
print(add2(2))  #result2 = 2
print(add2(6))  #result2 = 8   result2에 누적 됨

2
8


In [136]:
class Caculator:
    def __init__(self): #__init__  class -> 객체 생성될 때 자동 호출(생성자)
        self.result = 0
        print("생성자 호출됨")
        
    def add(self, num):
        self.result += num
        print("add함수 호출됨")
        return self.result

In [138]:
cal1 = Caculator() # class -> 객체 생성
cal2 = Caculator() # class -> 객체 생성

생성자 호출됨
생성자 호출됨


In [140]:
cal1.add(3)

add함수 호출됨


3

In [141]:
cal1.add(4)

add함수 호출됨


7

In [142]:
cal2.add(2)

add함수 호출됨


2

In [143]:
cal2.add(6)

add함수 호출됨


8

In [200]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [201]:
torch.manual_seed(1)

In [202]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [203]:
x_train.shape

torch.Size([3, 1])

In [204]:
W = torch.zeros(1, requires_grad = True) #requires_grad = True는 W는 변수

In [205]:
b = torch.zeros(1, requires_grad = True) #requires_grad = True는 b는 변수

In [206]:
# 초기 모델 가설함수 : y = 0 * x + 0

In [207]:
# hx = W * x_train + b

In [208]:
# hx

In [209]:
#cost 함수

# cost = torch.mean((hx - y_train) ** 2)
# cost

In [210]:
# optimizer = optim.SGD([W,b], lr = 0.01)


In [211]:
#미분을 해서 구한 기울기를 0으로 초기화 해줌
# optimizer.zero_grad()#미분을 해서 구한 기울기를 0으로 초기화해줌
# cost.backward() #W, b에 대한 기울기가 계산
# optimizer.step()#W,b에 대한 업데이트

In [212]:
for epoch in range(2000):
    hx=W * x_train + b
    cost=torch.mean((hx - y_train)**2)
    optimizer=optim.SGD([W,b],lr=0.01) #lr == learning_rate
    optimizer.zero_grad()#미분을 해서 구한 기울기를 0으로 초기화해줌
    cost.backward() #W, b에 대한 기울기가 계산
    optimizer.step()#W,b에 대한 업데이트
    if epoch%100 ==0:
        print(epoch,  W.item(), b.item(), cost.item())

0 0.18666668236255646 0.07999999821186066 18.66666603088379
100 1.7456912994384766 0.5780722498893738 0.04817060008645058
200 1.80009925365448 0.4544214904308319 0.029766537249088287
300 1.8428597450256348 0.35721680521965027 0.018393920734524727
400 1.876473307609558 0.28080499172210693 0.011366334743797779
500 1.9028971195220947 0.22073803842067719 0.007023668382316828
600 1.9236682653427124 0.1735200434923172 0.00434019835665822
700 1.9399964809417725 0.13640251755714417 0.0026819754857569933
800 1.952831506729126 0.10722480714321136 0.0016572937602177262
900 1.9629212617874146 0.0842885971069336 0.0010241125710308552
1000 1.9708527326583862 0.06625857204198837 0.0006328357267193496
1100 1.977087378501892 0.05208539217710495 0.0003910581872332841
1200 1.9819889068603516 0.04094360023736954 0.0002416476490907371
1300 1.9858416318893433 0.032185304909944534 0.00014932315389160067
1400 1.9888702630996704 0.025300635024905205 9.227206464856863e-05
1500 1.991250991821289 0.01988868787884

In [213]:
W

tensor([1.9974], requires_grad=True)

In [214]:
b

tensor([0.0060], requires_grad=True)

In [215]:
W.item()
b.item()

0.005984552204608917

In [216]:
b.item()

0.005984552204608917

In [217]:
W #W == 2

tensor([1.9974], requires_grad=True)

In [218]:
b  #b == 0

tensor([0.0060], requires_grad=True)

In [230]:
W.item()*7 + b.item()

13.987556226551533

In [220]:
w = torch.tensor(2.0, requires_grad=True)

In [221]:
y = w**2

In [222]:
y

tensor(4., grad_fn=<PowBackward0>)

In [223]:
z = 2*y+5

In [224]:
z

tensor(13., grad_fn=<AddBackward0>)

In [225]:
z.backward()

In [227]:
w.grad #z수식을 w로 미분한 값

tensor(8.)

In [257]:
x1_train = torch.FloatTensor([[73], [93], [89], [96], [73]])
x2_train = torch.FloatTensor([[80], [88], [91], [98], [66]])
x3_train = torch.FloatTensor([[75], [93], [90], [100], [70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [258]:
x1_train.shape

torch.Size([5, 1])

In [259]:
w1 = torch.zeros(1, requires_grad=True)
w2 = torch.zeros(1, requires_grad=True)
w3 = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

In [261]:
optimizer = optim.SGD([w1,w2, w3, b], lr = 0.00002) # lr = learning_rate

for epoch in range(2000):
    hx=w1 * x1_train + w2 * x2_train + w3 * x3_train + b
    cost=torch.mean((hx - y_train)**2)
    optimizer.zero_grad()#미분을 해서 구한 기울기를 0으로 초기화해줌
    cost.backward() #W, b에 대한 기울기가 계산
    optimizer.step()#W,b에 대한 업데이트
    if epoch%100 == 0:
        print(epoch,  w1.item(), w2.item(), w3.item(), b.item(), cost.item())

0 0.8123388290405273 0.5173814296722412 0.6807301640510559 0.013103491626679897 0.44850048422813416
100 0.8166012763977051 0.513529896736145 0.6803175210952759 0.013340798206627369 0.43186888098716736
200 0.8206796646118164 0.5099019408226013 0.6798658967018127 0.013576040044426918 0.41683053970336914
300 0.8245839476585388 0.5064858794212341 0.6793772578239441 0.013809289783239365 0.40320977568626404
400 0.8283229470252991 0.5032705068588257 0.6788539290428162 0.014040617272257805 0.3908737301826477
500 0.831904947757721 0.5002449750900269 0.6782981157302856 0.01427009142935276 0.37968748807907104
600 0.8353383541107178 0.4973990023136139 0.6777121424674988 0.014497769996523857 0.3695444166660309
700 0.8386306762695312 0.49472323060035706 0.6770973205566406 0.014723709784448147 0.3603190779685974
800 0.8417890667915344 0.49220871925354004 0.6764560341835022 0.014947976917028427 0.35193735361099243
900 0.844820499420166 0.4898463487625122 0.6757895946502686 0.015170615166425705 0.34428

In [262]:
w1.item()*90 + w2.item()*90 +w3.item()*90 +b.item()

180.96350336633623

In [263]:
x_train  =  torch.FloatTensor([[73,  80,  75], 
                               [93,  88,  93], 
                               [89,  91,  80], 
                               [96,  98,  100],   
                               [73,  66,  70]])  
y_train  =  torch.FloatTensor([[152],  [185],  [180],  [196],  [142]])

In [264]:
print(x_train.shape)
print(y_train.shape)

torch.Size([5, 3])
torch.Size([5, 1])


In [265]:
#w1 = torch.zeros(1, requires_grad=True)
#w2 = torch.zeros(1, requires_grad=True)
#w3 = torch.zeros(1, requires_grad=True)

W = torch.zeros((3,1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)

In [266]:
W

tensor([[0.],
        [0.],
        [0.]], requires_grad=True)

In [270]:
optimizer = optim.SGD([W, b], lr = 0.00001)
for epoch in range(2000):
    hx=x_train.matmul(W) + b
    cost=torch.mean((hx - y_train)**2)
    optimizer.zero_grad()#미분을 해서 구한 기울기를 0으로 초기화해줌
    cost.backward() #W, b에 대한 기울기가 계산
    optimizer.step()#W,b에 대한 업데이트
    if epoch%100 ==0:
        print(epoch, cost.item())

0 0.6441253423690796
100 0.6243399977684021
200 0.6053057909011841
300 0.5869807600975037
400 0.5693574547767639
500 0.552388608455658
600 0.536058783531189
700 0.5203513503074646
800 0.5052306056022644
900 0.49067097902297974
1000 0.47666364908218384
1100 0.4631773829460144
1200 0.4501873850822449
1300 0.4376913011074066
1400 0.42565807700157166
1500 0.4140707850456238
1600 0.4029100835323334
1700 0.3921758532524109
1800 0.3818321228027344
1900 0.3718731105327606


In [271]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [272]:
torch.manual_seed(1)

In [273]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [274]:
model = nn.Linear(1,1) #입력차원, 출력차원

In [275]:
list(model.parameters()) #w, b 값
#초기모델 : y = 0.5153 * x_train -0.4414

[Parameter containing:
 tensor([[0.5153]], requires_grad=True),
 Parameter containing:
 tensor([-0.4414], requires_grad=True)]

In [277]:
optimizer = torch.optim.SGD(model.parameters(), lr = 0.01)

In [279]:
for epoch in range(2000):
    hx = model(x_train) #hx=x_train.matmul(W) + b
    cost = F.mse_loss(hx, y_train) #cost=torch.mean ((hx - y_train)**2)

    optimizer.zero_grad()#미분을 해서 구한 기울기를 0으로 초기화해줌
    cost.backward() #W, b에 대한 기울기가 계산
    optimizer.step()#W,b에 대한 업데이트
    if epoch%100 ==0:
        print(epoch, cost.item())

0 13.103541374206543
100 0.00279058120213449
200 0.00172441138420254
300 0.0010655784280970693
400 0.0006584661896340549
500 0.0004068926500622183
600 0.0002514346851967275
700 0.00015537298168055713
800 9.601024794392288e-05
900 5.9327696362743154e-05
1000 3.66610438504722e-05
1100 2.2655576685792767e-05
1200 1.3999051589053124e-05
1300 8.65114816406276e-06
1400 5.346103989722906e-06
1500 3.3032331430149497e-06
1600 2.04174443751981e-06
1700 1.2618406799447257e-06
1800 7.801028800713539e-07
1900 4.823282324650791e-07


In [280]:
list(model.parameters())

[Parameter containing:
 tensor([[1.9994]], requires_grad=True),
 Parameter containing:
 tensor([0.0014], requires_grad=True)]

In [284]:
new_var = torch.FloatTensor([[4.0]])
model(new_var)

tensor([[7.9989]], grad_fn=<AddmmBackward0>)

In [285]:
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [286]:
model = nn.Linear(3,1) #입력차원, 출력차원

In [287]:
list(model.parameters())

[Parameter containing:
 tensor([[-0.1119,  0.2710, -0.5435]], requires_grad=True),
 Parameter containing:
 tensor([0.3462], requires_grad=True)]

In [288]:
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)

In [289]:
for epoch in range(2000):
    hx = model(x_train) #hx=x_train.matmul(W) + b
    cost = F.mse_loss(hx, y_train) #cost=torch.mean ((hx - y_train)**2)

    optimizer.zero_grad()#미분을 해서 구한 기울기를 0으로 초기화해줌
    cost.backward() #W, b에 대한 기울기가 계산
    optimizer.step()#W,b에 대한 업데이트
    if epoch%100 ==0:
        print(epoch, cost.item())

0 42134.70703125
100 5.960053443908691
200 5.654706954956055
300 5.365412712097168
400 5.091428756713867
500 4.831833839416504
600 4.585997104644775
700 4.353074550628662
800 4.132411003112793
900 3.9234554767608643
1000 3.7255024909973145
1100 3.5379719734191895
1200 3.360325574874878
1300 3.19205641746521
1400 3.0326738357543945
1500 2.881699562072754
1600 2.7386722564697266
1700 2.603201150894165
1800 2.4748456478118896
1900 2.353286027908325


In [290]:
new_var = torch.FloatTensor([[90,90,90]])
model(new_var)

tensor([[181.3557]], grad_fn=<AddmmBackward0>)

In [291]:
list(model.parameters())

[Parameter containing:
 tensor([[0.8540, 0.8475, 0.3096]], requires_grad=True),
 Parameter containing:
 tensor([0.3568], requires_grad=True)]